### ISSUE TITLE
Act cannot run OpenTofu from a Windows host

### ISSUE THREAD

**Issue by rdctmeconomou** [ResearchDataCom/get-good-with-gitops#17]
The file /tmp/*/tofu is a Node.js program that ought to be executable.  When running Act on a Windows host, this file is not executable, causing `tofu init` to fail.  My guess is that the Node.js program gets downloaded to a temporary directory backed by an NTFS volume, where it loses the executable bit.  This is likely a bug in opentofu/setup-opentofu@v1.0.2.

As a workaround, add a step that makes that file executable.  For example:

```yaml
      # Initialize OpenTofu and deploy the stack.
      - uses: opentofu/setup-opentofu@v1.0.2
      - run: chmod a+x /tmp/*/tofu
      - run: tofu init
```
